### ISSUE TITLE
alignment of educational details

### ISSUE THREAD

**Issue by IAmSurajBobade** [IAmSurajBobade/IAmSurajBobade.github.io#11]

**Comment by mrunal-selokar** [comment]
Mi te muddam alternate kel hot, to look like design


________________________________

**Comment by IAmSurajBobade** [comment]
design is poor if not understood by the viewer!
you may add my 4th standard school if you want, so that it will look like a design and not a bug.
or make it aline.

**Comment by mrunal-selokar** [comment]
theres nothing poor in design. It was alternate pattern and has same height as of skills section. If you like, will change everything to left aligned

**Comment by mrunal-selokar** [comment]
All schools aligned to left

**Comment by mrunal-selokar** [comment]
resolved and deployed
