### ISSUE TITLE
size of green box for Ceritifications, volunteer Experiences, organizations

### ISSUE THREAD

**Issue by IAmSurajBobade** [IAmSurajBobade/IAmSurajBobade.github.io#12]
can you make the size non-static? it would be good if size is comparable with skills section hegiht and width

**Comment by mrunal-selokar** [comment]
Its not static adjusted automatically with others
________________________________

**Comment by IAmSurajBobade** [comment]
Then make it adjust in comparable height and width.
It is too small according to other cards, and it shows lot of empty space

**Comment by mrunal-selokar** [comment]
That section needs to be modifies. Suggest if anything can be added there

**Comment by mrunal-selokar** [comment]
Career experience can be added. Internship and then the job

**Comment by IAmSurajBobade** [comment]
good points. lets discuss over in person
